spring:
  application:
    name: mb
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    view:
      prefix: templates
      suffix: .html
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          [
              'env',
              'health',
              'info',
              'logfile',
              'loggers',
              'threaddump',
              'liquibase',
              'mappings'
          ]
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db



omdb:
  server:
    url: https://www.omdbapi.com

