spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:mb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    username: sa
    password: admin
    hikari:
      poolName: Hikari
      auto-commit: false

  jpa:
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
