management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          [
              'env',
              'health',
              'info',
              'logfile',
              'loggers',
              'threaddump',
              'liquibase',
              'mappings'
          ]
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db

omdb:
  server:
    url: https://www.omdbapi.com

spring:
  application:
    name: mb
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  mvc:
    view:
      prefix: templates
      suffix: .html
  profiles:
    active: dev
  sql:
    init:
      mode: always
  liquibase:
    change-log: db/changelog/changelog-master.xml

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub